name: Publish NPM

on:
 release:
  types: [created]

jobs:
 publish-npm:
  name: Publish to NPM
  runs-on: ubuntu-latest
  permissions:
   contents: read
   packages: write
   id-token: write
  strategy:
   fail-fast: false
   matrix:
    node: ['lts/*']
  steps:
   - name: 📥 Checkout code
     uses: actions/checkout@v4
   - name: 📦 Setup PNPM
     uses: pnpm/action-setup@v4
     with:
      standalone: true
   - name: 📦 Setup Node.js ${{ matrix.node }}
     uses: actions/setup-node@v4
     with:
      node-version: ${{ matrix.node }}
      always-auth: true
      cache: 'pnpm'
   - name: 🚀 Install dependencies
     run: pnpm install
   - name: 🚀 Build packages
     run: pnpm build
   - name: 📦 Deploy Package to NPM Packages
     env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
     run: |
      npm config set registry https://registry.npmjs.org
      npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      pnpm publish --access public --no-git-checks --provenance
